<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- BASIC -->
    <xacro:macro name="wheel_link" params="wheel_name radius thickness">
        <link name="${wheel_name}_link">
            <visual>
                <origin xyz="0 0 ${thickness/2}" />
                <geometry>
                    <cylinder length="${thickness}" radius="${radius}" />
                </geometry>
            </visual>
        </link>
    </xacro:macro>

    <xacro:macro name="wheel_joint"
        params="wheel_name direction:=1 friction:=0.0 damping:=0 *parent *origin">
        <joint name="${wheel_name}_joint" type="continuous">
            <axis xyz="0 0 ${direction}" />
            <xacro:insert_block name="parent" />
            <child link="${wheel_name}_link" />
            <xacro:insert_block name="origin" />
            <!-- dynamics-->
            <dynamics friction="{friction}" damping="${damping}" />
        </joint>
    </xacro:macro>

    <xacro:macro name="wheel"
        params="name direction:=1 radius:=0.02 thickness:=0.01 friction:=0.0 damping:=0 *parent *origin">
        <xacro:wheel_link wheel_name="${name}" radius="${radius}" thickness="${thickness}" />

        <xacro:wheel_joint wheel_name="${name}" direction="${direction}" friction="${friction}"
            damping="${damping}">
            <xacro:insert_block name="parent" />
            <xacro:insert_block name="origin" />
        </xacro:wheel_joint>
    </xacro:macro>

    <!-- STEERING -->
    <xacro:macro name="wheel_steering_link" params="wheel_name">
        <link name="${wheel_name}_steering_link"></link>
    </xacro:macro>

    <xacro:macro name="wheel_steering_joint"
        params="wheel_name direction:=1 friction=1.0 damping:=1 *parent *origin">
        <joint name="${wheel_name}_steering_joint" type="revolute">
            <axis xyz="0 ${direction} 0" />
            <xacro:insert_block name="parent" />
            <child link="${wheel_name}_steering_link" />
            <xacro:insert_block name="origin" />
            <!-- limits -->
            <limit effort="100" lower="-0.41" upper="0.41" velocity="0.5" />
            <!-- dynamics-->
            <dynamics friction="${friction}" damping="${damping}" />
        </joint>
    </xacro:macro>

    <xacro:macro name="wheel_steered"
        params="name direction:=1 radius:=0.02 thickness:=0.01 friction:=0.0 damping:=0 steering_friction:=1.0 steering_damping:=1 *parent *origin">
        <xacro:wheel_link wheel_name="${name}" radius="${radius}" thickness="${thickness}" />

        <xacro:wheel_steering_link wheel_name="${name}" />

        <xacro:wheel_joint wheel_name="${name}" direction="${direction}"
            friction="${friction}" damping="${damping}">
            <parent link="${name}_steering_link" />
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:wheel_joint>

        <xacro:wheel_steering_joint wheel_name="${name}" direction="${direction}"
            friction="${steering_friction}" damping="${steering_damping}">
            <xacro:insert_block name="parent" />
            <xacro:insert_block name="origin" />
        </xacro:wheel_steering_joint>
    </xacro:macro>

</robot>